# Generated by Django 5.2 on 2025-12-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
