# Generated by Django 5.2 on 2025-12-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='img_url',
            field=models.CharField(max_length=2000),
        ),
    ]
