# Generated by Django 5.2 on 2025-12-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuitem_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='img_url',
            field=models.CharField(default='static/Images/', max_length=2000),
        ),
    ]
