# Generated by Django 5.2 on 2026-01-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], max_length=10),
        ),
    ]
