# Generated by Django 5.2 on 2026-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
