# Generated by Django 5.2 on 2026-01-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_status_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
