# Generated by Django 5.2 on 2026-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SELECT STATUS', 'Select Status'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='SELECT STATUS', max_length=13),
        ),
    ]
