# Generated by Django 5.2 on 2026-02-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_status_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card')], default='CASH', max_length=20),
        ),
    ]
